---
infinispan_url: "site1-datagrid1{{ domain_name }}"
jdg_jgroups_relay_site: site1
jbcs_host: "site1-loadbalancer{{ domain_name }}"
keycloak_modcluster_url: "site1-loadbalancer{{ domain_name }}"
jdg_jdbc_url: jdbc:mariadb://site1-database1.mariadb.database.azure.com:3306/keycloak
keycloak_jdbc_url: jdbc:mariadb://site1-database1.mariadb.database.azure.com:3306/keycloak

jdg_jdbc_user: "keycloak-user@site1-database1"
jdg_jdbc_pass: "redhat1!"
