---
collections:
  - name: middleware_automation.redhat_csp_download
    version: ">=1.2.1"
  - name: middleware_automation.infinispan
    version: ">=0.0.6"
  - name: middleware_automation.keycloak
    version: ">=0.0.2"
  - name: mrlesmithjr.mariadb_galera_cluster
  - name: community.general
  - name: community.postgresql
