FROM registry.access.redhat.com/ubi8/ubi:8.4

RUN yum install -y yum-utils hostname net-tools iproute bind-utils \
                   glibc-locale-source glibc-langpack-en procps-ng \
                   firewalld unzip mailcap python39 python3-dnf systemd; \
    yum clean all

RUN cd /lib/systemd/system/sysinit.target.wants/; \
    for i in *; do [ $i = systemd-tmpfiles-setup.service ] || rm -f $i; done

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/basic.target.wants/* \
    /lib/systemd/system/anaconda.target.wants/*

VOLUME [ "/tmp", "/run", "/run/lock" ]
CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target" ]
