---
collections:
  - name: middleware_automation.redhat_csp_download
    version: ">=1.2.1"
  - name: middleware_automation.infinispan
    version: ">=0.1.6"
  - name: middleware_automation.keycloak
    version: ">=0.2.0"
  - name: community.general
