---
collections:
  - name: middleware_automation.redhat_csp_download
    version: ">=1.2.1"
  - name: middleware_automation.infinispan
    version: ">=1.0.1"
  - name: middleware_automation.keycloak
    version: ">=1.0.1"
  - name: community.general
  - name: community.mysql
  - name: ansible.posix
