---
- assert:
    that:
      - httpd is defined
      - httpd.user is defined
      - httpd.user.name is defined
      - httpd.group is defined
      - httpd.group.name is defined
      - httpd.home is defined
    quiet: true

- group:
    name: "{{ httpd.group.name }}"
    state: present
    gid: "{{ httpd.group.id | default(omit) }}"

- user:
    name: "{{ httpd.user.name }}"
    state: present
    uid: "{{ httpd.user.id | default(omit) }}"

- file:
    path: "{{ httpd.home }}"
    owner: "{{ httpd.user.name }}"
    group: "{{ httpd.group.name }}"
    recurse: true
  changed_when: false

- set_fact:
    zip_file_repo: /opt/apps

- file:
    path: "{{ zip_file_repo }}"
    state: directory

- name: Download JBoss Core Services from CSP
  redhat_csp_download:
    url: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=103291&product=core.service.apachehttp"
    dest: "{{ zip_file_repo }}/jbcs.zip"
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
  when:
    - not jbcs_installed is defined

- stat:
    path: "{{ httpd.home }}/httpd"
  register: httpd_home

- name: Unarchive JBoss Core Services
  unarchive:
    src: "{{ zip_file_repo }}/jbcs.zip"
    remote_src: yes
    dest: /opt
  when:
    - not httpd_home.stat.exists

- name: "Post install HTTPD"
  command:
    cmd: "{{ httpd.home }}/httpd/.postinstall.systemd"
    chdir: "{{ httpd.home }}/httpd/"
    creates: /usr/lib/systemd/system/jbcs-httpd24-httpd.service

- name: "Ensures JBCS configuration is correct"
  template:
    src: templates/httpd.conf.j2
    dest: /opt/jbcs-httpd24-2.4/httpd/conf/httpd.conf
  notify:
    - "Restart JBCS"

- name: "Start HTTPd Service"
  service:
    name: jbcs-httpd24-httpd.service
    state: started
    enabled: yes

- name: "Wait for all used ports to be open"
  wait_for:
    port: "{{ item }}"
    delay: 0
  loop:
    - 80
    - 443
    - 6666
  when:
    - check_jbcs_port is defined
