---
- name: Prepare
  hosts: all
  serial: 2
  tasks:
    - name: Install required packages
      yum:
        use_backend: dnf
        name: 
          - bind-utils
          - glibc-locale-source
          - glibc-langpack-en
          - mailcap
          - unzip
        state: present
