---
dependency:
  name: shell
  command: ansible-galaxy collection install -r molecule/docker/requirements.yml -p $HOME/.ansible/collections --force-with-deps
driver:
  name: docker
platforms:
  - name: site1-database1
    hostname: site1-database1.rhssocrossdc.com
    image: centos:8
    privileged: true
    command: "/lib/systemd/systemd log-level=info unit=sysinit.target"
    groups:
      - database
      - site1
    networks:
      - name: site1
      - name: site2
    network_mode: site1
  - name: site2-database1
    hostname: site2-database1.rhssocrossdc.com
    image: centos:8
    privileged: true
    command: "/lib/systemd/systemd log-level=info unit=sysinit.target"
    groups:
      - database
      - site2
    networks:
      - name: site1
      - name: site2
    network_mode: site2
  - name: site1-datagrid1
    hostname: site1-datagrid1.rhssocrossdc.com
    image: centos:8
    privileged: true
    command: "/usr/sbin/init"
    groups:
      - datagrid
      - site1
    networks:
      - name: site1
      - name: site2
    network_mode: site1
  - name: site1-datagrid2
    hostname: site1-datagrid2.rhssocrossdc.com
    image: centos:8
    privileged: true
    command: "/lib/systemd/systemd log-level=info unit=sysinit.target"
    groups:
      - datagrid
      - site1
    networks:
      - name: site1
      - name: site2
    network_mode: site1
  - name: site2-datagrid1
    hostname: site2-datagrid1.rhssocrossdc.com
    image: centos:8
    privileged: true
    command: "/lib/systemd/systemd log-level=info unit=sysinit.target"
    groups:
      - datagrid
      - site2
    networks:
      - name: site1
      - name: site2
    network_mode: site2
  - name: site2-datagrid2
    hostname: site2-datagrid2.rhssocrossdc.com
    image: centos:8
    privileged: true
    command: "/lib/systemd/systemd log-level=info unit=sysinit.target"
    groups:
      - datagrid
      - site2
    networks:
      - name: site1
      - name: site2
    network_mode: site2
  - name: site1-rhsso1
    hostname: site1-rhsso1.rhssocrossdc.com
    image: centos:8
    privileged: true
    command: "/lib/systemd/systemd log-level=info unit=sysinit.target"
    groups:
      - rhsso
      - site1
    networks:
      - name: site1
      - name: site2
    network_mode: site1
  - name: site2-rhsso1
    hostname: site2-rhsso1.rhssocrossdc.com
    image: centos:8
    privileged: true
    command: "/lib/systemd/systemd log-level=info unit=sysinit.target"
    groups:
      - rhsso
      - site2
    networks:
      - name: site1
      - name: site2
    network_mode: site2
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
    ssh_connection:
      pipelining: false
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: converge.yml
  env:
    ANSIBLE_FORCE_COLOR: "true"
  inventory:
    links:
      group_vars: ../group_vars
    all:
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # -   idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
