---
- name: Prepare
  hosts: all
  tasks:
    - debug:
        msg: "Prepare"
    - name: Install sudo
      ansible.builtin.yum:
        name:
          - sudo
          - java-1.8.0-openjdk-headless
          - firewalld
          - ca-certificates
