---
collections:
  - name: middleware_automation.redhat_csp_download
    version: ">=1.2.1"
  - name: git@github.com:ansible-middleware/infinispan.git
    scm: git
    version: main
  - name: git@github.com:ansible-middleware/keycloak.git
    scm: git
    version: main
  - name: community.general
  - name: community.mysql
  - name: ansible.posix
  - name: ansible.netcommon
  - name: community.docker
    version: ">=1.9.1"
