---
- name: Playbook for loadbalancer Hosts
  hosts: loadbalancer
  collections:
    - middleware_automation.redhat_csp_download
  roles:
    - redhat_csp_download
  tasks:
    - name: "JBoss Core Services"
      include_role:
        name: jbcs