---
- name: Playbook for rhsso Hosts
  hosts: rhsso
  become: true
  collections:
    - middleware_automation.redhat_csp_download
    - middleware_automation.keycloak
  roles:
    - redhat_csp_download
  tasks:
    - name: Keycloak Role
      include_role:
        name: keycloak
      vars:
        keycloak_admin_password: "{{ admin_pass }}"
