---
- name: Playbook for rhsso Hosts
  hosts: rhsso
  become: true
  collections:
    - middleware_automation.redhat_csp_download
    - middleware_automation.keycloak
  roles:
    - redhat_csp_download
    - name: keycloak
      keycloak_admin_password: "{{ admin_pass }}"
