---
name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.9"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: cross-dc-rhsso-demo

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install yamllint, ansible and molecule
        run: |
          python -m pip install --upgrade pip
          pip install yamllint 'molecule[docker]~=3.5.2' 'molecule[podman]~=3.5.2' ansible==2.9.27 netaddr flake8 ansible-lint voluptuous

      # - name: Run sanity tests
      #   run: ansible-test sanity

      - name: Run molecule test
        run: |
          molecule test --scenario-name=podman
        working-directory: ./cross-dc-rhsso-demo
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
